repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.25.1           # pin to your ESLint version
    hooks:
      - id: eslint
        name: ESLint via pnpm for api
        entry: pnpm lint-api
        pass_filenames: false